### ISSUE TITLE
Cannot login?

### ISSUE THREAD

**Issue by xunge** [StrayCamel247/Django_web#23]
Hi, I am really interested in your project and want to run it. However, I cannot log in because I do not have the database information. Will you provide the detailed structure of the created tables?

**Comment by StrayCamel247** [comment]
Hi, Today i fix somes bugs about login and other apis, also register a linux server ,u can view a demo on site:http://47.114.93.191:422/, thx for your interset, wove u : )（￣︶￣）↗

**Comment by StrayCamel247** [comment]
Any bugs u meet, email me or issue here, i'll fix in the first time

**Comment by xunge** [comment]
Thanks! Perfect work
